# Generated by Django 5.1.4 on 2024-12-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_collection_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviews",
            new_name="Review",
        ),
    ]
