# Generated by Django 5.1.4 on 2024-12-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_reviews_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
