# Generated by Django 5.1.4 on 2024-12-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_order_options_alter_customer_birth_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
    ]
