# Generated by Django 5.1.4 on 2025-01-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_review_user_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
