# Generated by Django 5.1.5 on 2025-01-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_review_stars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
