# Generated by Django 5.1.5 on 2025-02-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
