# Generated by Django 5.1.5 on 2025-02-23 09:25

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_productimage_image_productimage_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_data',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='', upload_to='store/images', validators=[store.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
