# Generated by Django 5.1.5 on 2025-02-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_productimage_image_data_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
