# Generated by Django 5.1.5 on 2025-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_address_address_type_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('H', 'Home'), ('W', 'Work')], default='shipping', max_length=10),
        ),
    ]
