# Generated by Django 5.1.5 on 2025-03-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('H', 'Home'), ('W', 'Work')], default='H', max_length=10),
        ),
    ]
